/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterface;

import CapaNegocio.ClsMateria;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class WinMateria extends javax.swing.JFrame {

    /**
     * Creates new form WinMateria
     */
    String nombre;
    int cupo;
    public WinMateria() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0,216,209));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtMateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtCupo = new javax.swing.JTextField();
        BtnCrear = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();
        BrnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CmbMateria = new javax.swing.JComboBox<>();
        LblMensaje = new javax.swing.JLabel();
        BrnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proceso Creación e Inscripción Materias");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nombre Materia: ");

        jLabel2.setText("Cupo Máximo: ");

        TxtCupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCupoActionPerformed(evt);
            }
        });

        BtnCrear.setText("Crear");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        BtnRetornar.setText("Retornar");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        BrnLimpiar.setText("Limpiar");
        BrnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Lista Materias:");

        CmbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        CmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbMateriaActionPerformed(evt);
            }
        });

        BrnListar.setText("Listar");
        BrnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCrear)
                                .addGap(18, 18, 18)
                                .addComponent(BrnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(BrnListar)
                                .addGap(74, 74, 74)
                                .addComponent(BtnRetornar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtMateria)
                                    .addComponent(TxtCupo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addComponent(CmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(CmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrear)
                    .addComponent(BtnRetornar)
                    .addComponent(BrnLimpiar)
                    .addComponent(BrnListar))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        int k=WinEduca.lst.numeromat;
        boolean bandera=false;
        nombre=TxtMateria.getText();
        cupo=Integer.parseInt(TxtCupo.getText());;
        for(int i=0; i<k; i++){
            if(WinEduca.lst.lstmat[i].getNombre().equals(nombre)){
                bandera=true;
            }
        }
        if(!bandera){
            WinEduca.lst.lstmat[k]= new ClsMateria(nombre,cupo);
            LblMensaje.setText("CREACION EXITOSA");
        }else{
            LblMensaje.setText("MATERIA EXISTENTE");
            BtnCrear.setEnabled(false);
        }
        k++;
        WinEduca.lst.numeromat=k;
        TxtMateria.setText(null);
        TxtMateria.requestFocus();
        TxtCupo.setText(null);
        
        
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        CmbMateria.removeAllItems();
        LblMensaje.setText(null);
        String Linea;
        int k=WinEduca.lst.numeroest;

        for(int i=0; i<k; i++){
            Linea=WinEduca.lst.lstest[i].getCedula()+ ",";
            Linea+=WinEduca.lst.lstest[i].getNombre();
        }  
    }//GEN-LAST:event_formWindowActivated

    private void BrnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnLimpiarActionPerformed
        // TODO add your handling code here:
        TxtMateria.setText(null);
        TxtCupo.setText(null);
        LblMensaje.setText(null);
        TxtMateria.requestFocus();
    }//GEN-LAST:event_BrnLimpiarActionPerformed

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        // TODO add your handling code here:
        new WinEduca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void CmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbMateriaActionPerformed

    }//GEN-LAST:event_CmbMateriaActionPerformed

    private void TxtCupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCupoActionPerformed

    private void BrnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrnListarActionPerformed
        // TODO add your handling code here:
        LblMensaje.setText(null);
        String Linea;
        int m=WinEduca.lst.numeromat;
        CmbMateria.removeAllItems();
        for(int i=0; i<m; i++){
            Linea=WinEduca.lst.lstmat[i].getNombre()+ ",";
            Linea+=WinEduca.lst.lstmat[i].getNumest();
            CmbMateria.addItem(Linea);
        }
    }//GEN-LAST:event_BrnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrnLimpiar;
    private javax.swing.JButton BrnListar;
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JComboBox<String> CmbMateria;
    private javax.swing.JLabel LblMensaje;
    private javax.swing.JTextField TxtCupo;
    private javax.swing.JTextField TxtMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
